### ISSUE TITLE
[항목1-1] p.53 매개 변수 전달 방법 무엇을 선택할까?

### ISSUE THREAD

**Issue by chae9606** [cppmm-developer/effective_cpp#1]
항목1 마지막 부분 예시가 궁금합니다.
효과적인 C++ 프로그램을 위해서는 서브 언어인 C, STL, 템플릿, 객체 지향 개념을 오가며 상황에 맞게 대응해야 한다고 하는데요.
마지막 부분에 예시를 들기 위해 '값 전달, 참조 전달 중 효율이 좋은 것'에 대한 내용이 나옵니다.
C 스타일, 객체 지향 C++, 템플릿 C++, STL 마다 다르다고 하는데 코드로 예시를 들어주면 좋을 것 같습니다.
:)

**Comment by hwayoungBaek** [comment]
Q. 효율이 좋은 것은? 값 전달 vs 참조 전달 

A.
'값에 의한 전달'이 효율 더 좋은 경우: 기본제공 타입(Primitive built-in types), STL 반복자, 함수 객체 타입
'참조에 의한 전달'이 효율 더 좋은 경우: 위 세 가지를 제외한 모든 경우

이를 이해하기 위해 매개변수를 '값에 의한 전달' 방식으로 전달할 때 어떠한 연산이 수행되는지 설명하겠습니다.
```
bool IsValid(Widget w);

Widget widget_a;
bool isOk = IsValid(widget_a);  // (1)
```
(1)에서 widget_a는 매개변수 w로 넘어가면서 Widget의 복사생성자가 호출됩니다. 그리고 IsValid()함수가 종료되면서 소멸자가 호출되게 됩니다. 결과적으로 생성자 한 번, 소멸자 한 번 호출되게 됩니다.
만약 Widget이 다른 클래스로부터 상속받는 파생클래스이고 멤버 변수를 여럿 가지고 있다면 더욱더 고비용의 연산이 수행될 것입니다.

따라서 대부분의 경우 '참조에 의한 전달'이 더욱 효율적입니다.


그러나 기본제공 타입, STL 반복자, 함수 객체 타입의 경우 '값에 의한 전달'이 더욱 효율이 좋습니다.
그 이유는 아래와 같습니다.
- 기본제공타입은 복사 비용이 작고 고정되어 있습니다. (이슈 항목 4-1)
- 반복자와 함수 객체는 처음부터 복사 효율을 높여서 설계하였습니다.
- 반복자와 함수 객체는 처음부터 복사손실 문제에 노출되지 않도록 설계하였습니다.
- 사용자 정의 타입의 크기는 언제는 변화할 수 있기 때문에 복사를 최대한 지양하는 것이 좋지만, 위의 세 개는 아니다.


참고: 책 Effective C++ 항목20

**Comment by chae9606** [comment]
감사합니당!
반복자와 함수 객체는 복사 효율을 높여 설계했다는게 흥미롭네요!
