### ISSUE TITLE
[항목11-1]pg109. CPU 명령어 선행인출, 캐시, 파이프라이닝 효과가 떨어지는 이유

### ISSUE THREAD

**Issue by chae9606** [cppmm-developer/effective_cpp#13]
pg 109 마지막 줄에 있는 문장입니다!
'CPU 명령어 선행인출, 캐시, 파이프라이닝 등의 효과가 떨어질 수 있고요.'

어떤 경우에 효과가 떨어지는지 궁금합니다!
어떤 이유로 분기가 추가되면 효과가 떨어지는지도 궁금합니다!

**Comment by shin0343** [comment]
컴파일러 최적화 내용 중에 '분기 최적화'라는 내용이 있는데요.
컴파일러는 분기 예측이 가능한 경우에 최적화가 됩니다.
즉, 조건문 내의 변수가 예측된 값으로 치환되고 파이프라이닝이 효과적으로 적용됩니다. 하지만 분기 예측이 힘든 경우에는 프로세서가 분기 명령을 만날 때마다 실행을 멈추고 분기의 비교 명령어 수행에 필요한 변수들을 알아내는 파이프라인이 모두 완료될 때까지 여러 사이클을 기다리게 됩니다. 이는 병목을 야기하여 파이프라이닝 효과가 떨어집니다.

해결책 : 조건문 코드를 수정 또는 순서 변경하여 예측하기 쉬운 분기로 개선

분기 예측이 가능한 예시코드
for(a=0; a<100; a++)
{
if( (a&1) == 0)
{ . . . }
else
{ . . . }
}

분기 예측이 힘든 예시코드
for(a=0; a<100; a++)
{
side = flipCoin(); // side의 값은 flipCoin()의 결과에 따라 달라지므로 예측하기 어렵다!
if( (side == HEADS)
{ . . . }
else
{ . . . }
}
