### ISSUE TITLE
[항목12-2] 사용자가 복사 함수를 재정의해야 하는 경우?

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#15]
컴파일러가 기본적으로 복사 생성자와 복사 대입 연산자를 만들어주는데, 그것을 거절하고 개발자가 따로 재정의해야 하는 경우는 언제인가요? 이유도 함께 설명 부탁드립니다

**Comment by shin0343** [comment]
컴파일러가 기본적으로 만들어주는 복사 함수는 기본 타입에 대해서만 복사가 되므로 '완전 복사 함수'가 아닙니다.
따라서 '완전 복사'를 원하는 경우, 개발자가 따로 재정의 해야 합니다.

아래의 경우가 그 예시가 될 수 있겠네요. lastTransaction 변수는 기본적으로 복사되지 않기 때문에 개발자가 복사 함수를 재정의 해야 합니다.🥷

void logCall(const std::string& funcName);

class Customer
{
  public:
    ...
    Customer(const Customer& rhs);
    Customer& operator=(const Customer& rhs);
    ...
    
  private:
    std::string name;
    Date lastTransaction; // 기본적으로 복사되지 않는 데이터 멤버
};

// 복사 생성자
Customer::Customer(const Customer& rhs)
: name(rhs.name)
{
  logCall("Customer copy Constructor");
}

// 복사 대입 연산자
Customer& Customer::operator=(const Customer& rhs)
{
  logCall("Customer copy assignment operator");
  name = rhs.name;
  return *this;
}

**Comment by hwayoungBaek** [comment]
Q1. "컴파일러가 기본적으로 만들어주는 복사 함수는 기본 타입에 대해서만 복사가 되므로~" 에서 말하는 '기본 타입'이 built-in data type(int, boolean, char, float, ...)인가요? 

Q2. 예시 코드를 봤지만 잘 모르겠어요 :( 
개발자가 직접 구현한 복사 생성자와 복사대입연산자에서 date 클래스 복사가 누락되어서 잘못된거고, 만약  복사 함수 재정의를 아예 안했더라면 컴파일러에 의해 복사가 잘 될 것 같아요.
Date 클래스 예시로 작성해보았습니다.
```
class Date {
 public:
    Date() {};
    Date(std::string year, std::string month, std::string day)
        : year_(year), month_(month), day_(day) {
    };
    ~Date() {};
    
 private:
    std::string year_;
    std::string month_;
    std::string day_;

 public:
    std::string GetDateString() {
        return std::string(year_ +"."+month_+"."+day_);
    };
    
};


class Widget {
 public:
    Widget() {};
    ~Widget() {};
    
 public:
    std::string name_;
    Date today_;
};

int main()
{
    std::cout << "=== Default assign operator test ===" << std::endl;
    
    Widget widget_a;
    widget_a.name_ = "A";
    widget_a.today_ = Date("2023", "02", "20");
    
    Widget widget_a_copy;
    widget_a_copy = widget_a;
    
    std::cout << "widget_a_copy's name is " << widget_a_copy.name_ << std::endl;
    std::cout << "widget_a_copy's today is " << widget_a_copy.today_.GetDateString() << std::endl;

    return 0;
}
```

테스트 실행 결과
```
=== Default assign operator test ===
widget_a_copy's name is A
widget_a_copy's today is 2023.02.20
```

Q3. 기존 질문글에 의견 추가해봅니다~
'개발자가 복사함수를 재정의해야하는 경우는 멤버 변수에 포인터가 있을 때'라고 생각해왔습니다. 이게 맞는지 모르겠고, 맞다면 그 이유를 모르겠어요ㅜㅜ

**Comment by shin0343** [comment]
Q1. "컴파일러가 기본적으로 만들어주는 복사 함수는 기본 타입에 대해서만 복사가 되므로~" 에서 말하는 '기본 타입'이 built-in data type(int, boolean, char, float, ...)인가요?
**A1. 항목5에서는 "컴파일러가 모르는 자료형이거나 legal하지 않다면, resonable하지 않다면 생성하지 않음"이라는 것으로 보아 말씀하시는 타입도 해당 자료형에 해당합니다. STL의 경우에도 기본 복사 함수가 있다면 컴파일러가 복사함수를 기본으로 생성해줍니다.**

**Comment by shin0343** [comment]
Q3. 기존 질문글에 의견 추가해봅니다~
'개발자가 복사함수를 재정의해야하는 경우는 멤버 변수에 포인터가 있을 때'라고 생각해왔습니다. 이게 맞는지 모르겠고, 맞다면 그 이유를 모르겠어요ㅜㅜ
**A3. 복사 대상이 포인터, 참조자, 상수면 컴파일에 실패합니다. 이 경우에는 재정의하여야 하고, 첫번째 질문에 대한 답변과 같이 기본 타입(built-in data type과 기본 복사함수가 있는 STL 등)에 대해서는 컴파일러가 기본적으로 생성해줍니다.**

**Comment by shin0343** [comment]
Q2. 예시 코드를 봤지만 잘 모르겠어요 :(
개발자가 직접 구현한 복사 생성자와 복사대입연산자에서 date 클래스 복사가 누락되어서 잘못된거고, 만약 복사 함수 재정의를 아예 안했더라면 컴파일러에 의해 복사가 잘 될 것 같아요.
Date 클래스 예시로 작성해보았습니다.
**A2. Data클래스는 멤버가 모두 std::string이라서 기본 복사함수가 있는 데이터 멤버를 갖는 클래스라서 기본 복사함수가 제대로 생성되는 것 같습니다. Q3의 답변과 같이 '복사 대상이 포인터, 참조자, 상수'인 경우에 재정의를 해야하는 것 같네요.. 저도 답변하면서 배워가는..**

**Comment by hwayoungBaek** [comment]
- 좋은 글 찾아서 공유합니다. 

https://www.geeksforgeeks.org/assignment-operator-overloading-in-c/


- 위에 글 읽고 테스트 코드 수정해보았습니다.

포인터를 멤버변수로 가지고 있는 클래스 Date
Date에서는 복사대입연산자를 재정의하지 않습니다. (컴파일러에 의해 기본 대입연산자가 생성될 것이라고 예측할 수 있습니다. )

이 상황에서 Date 객체를 다른 객체로 복사했을 때 발생하는 문제점입니다.

```
// 복사 생성자, 복사대입연산자를 재정의하지 않은 클래스 Date
// 멤버 변수로 char*를 가지고 있음 (year_, month_, day_)
class Date {
 public:
    Date() {};
    Date(const char* year, const char* month, const char* day) {
        year_ = new char[strlen(year)+1];
        strcpy(year_, year);
        
        month_ = new char[strlen(month)+1];
        strcpy(month_, month);
        
        day_ = new char[strlen(day)+1];
        strcpy(day_, day);
    };
    ~Date() {};
    
 private:
    char* year_;
    char* month_;
    char* day_;

 public:
    std::string GetDateString() {
        return std::string(year_)+std::string(".")+std::string(month_)+std::string(".")+std::string(day_);
    };
    void SetYear(const char* year) {
        // year의 length 길이 같다는 가정하에
        strcpy(year_, year);
    }
};


class Widget {
 public:
    Widget() {};
    ~Widget() {};
    
 public:
    std::string name_;
    Date today_;
};

int main()
{
    std::cout << "=== Default assign operator test ===" << std::endl;
    
    Widget widget_a;
    widget_a.name_ = "A";
    widget_a.today_ = Date("2023", "02", "20");
    
    Widget widget_a_copy;
    widget_a_copy = widget_a;
    
    std::cout << "widget_a_copy's name is " << widget_a_copy.name_ << std::endl;
    std::cout << "widget_a_copy's today is " << widget_a_copy.today_.GetDateString() << std::endl;

    std::cout << "=== After chaning a's year ===" << std::endl;
    widget_a.today_.SetYear("1999");
    std::cout << "widget_a_copy's today is " << widget_a_copy.today_.GetDateString() << std::endl;
    return 0;
}
```

테스트 실행 결과
```
=== Default assign operator test ===
widget_a_copy's name is A
widget_a_copy's today is 2023.02.20
=== After chaning a's year ===
widget_a_copy's today is 1999.02.20
```

- 테스트 결과 설명
widget_a의 값을 변경하였는데 widget_a_copy의 값도 변화한 것을 볼 수 있습니다.

- 결론을 정리하자면 클래스 멤버 변수로 포인터가 있다고 해서 부분복사가 일어나는 것은 아닙니다. 전체적으로 복사는 잘 되지만 문제는 '얕은 복사'입니다.
원본 객체와 복사된 객체가 같은 주소를 가리키고 있어서, 원본 객체를 수정하면 복사된 객체에도 영향을 끼치는 것이 문제를 발생시키게 됩니다. 이런 이유로 복사대입연산자를 사용자가 직접 재정의하고 거기서 깊은 복사를 구현해줍니다.
