### ISSUE TITLE
[항목13-1]p.121 STL컨테이너의 경우엔 원소들이 정상적인 복사 동작을 해야하기 때문에 auto_ptr은 이들의 원소로 허용되지 않는 예시

### ISSUE THREAD

**Issue by shin0343** [cppmm-developer/effective_cpp#16]
STL컨테이너의 경우엔 원소들이 정상적인 복사 동작을 해야하기 때문에 auto_ptr은 이들의 원소로 허용되지 않는다고 합니다. 예시를 들어서 좀 더 설명해주실 수 있을까요??

**Comment by chae9606** [comment]
C++ Standard
auto_ptr does not meet the CopyConstructible and Assignable requirements for Standard Library container elements and thus instantiating a Standard Library container with an auto_ptr results in undefined behavior.

auto_ptr은 객체 복사 시 원본 객체를 null로 만듭니다.

[예시]
class X
{
};

std::vector<std::auto_ptr<X> > vecX;
vecX.push_back(new X);

std::auto_ptr<X> pX = vecX[0];  // vecX[0] is assigned NULL.


[unique_ptr을 원소로 가지는 STL Container 코드 예시]
vector의 push_back은 전달된 인자를 복사해서 넣기 때문에 복사생성자가 없는 unique_ptr에 사용할 수 없습니다.

int main() {
  std::vector<std::unique_ptr<A>> vec;
  std::unique_ptr<A> pa(new A(1));

  vec.push_back(std::move(pa));
  vec.emplace_back(new A(1));
}
