### ISSUE TITLE
[항목 18-1] 140p. 랩퍼타입을 struct로 만든 이유?

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#18]
140p 하단에 일, 월, 연을 구분하는 간단한 랩퍼(wrapper)타입을 코드로 보여주고 있습니다.
우리가 저번 스터디에서 class와 struct 의 차이는 없다고 결론을 지었는데, 이 책의 글쓴이가 랩퍼 타입을 굳이 struct로 만든 이유는 무엇일까요? 이것에 대한 재협님의 생각이 궁금합니다.
```
'struct' Day {
    explicit Day(int d) : val(d) {}
    int val;
};
```

**Comment by shin0343** [comment]
저희가 지난 번에 결론지었던 내용은 기존 c기반 코드와의 호환성 때문에 사용하는 것 같다고 했었죠.

저자가 struct를 사용한 이유는 아무래도 간단한 데이터를 담는 형태이므로 구조체를 사용한 것 같습니다. struct는 바이너리 데이터로 메모리 형태 그대로 변환이 가능하기 때문에 데이터를 주고 받을 때 이점이 있습니다. 아무래도 Day 구조체는 단순히 val 변수 하나를 갖기 때문에 이렇게 작성한게 아닐까 싶습니다.
