### ISSUE TITLE
[항목 18-2] 141p. 유효한 Month 의 집합을 미리 정의하는 방법 - 함수 / 객체

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#19]
141p 하단에 유효한 Month의 집합을 미리 정의해둔 코드에서 글쓴이는 아래와 같이 설명하고 있습니다. (코드 주석)
'유효한 Month 값을 반환하는 함수들. 이들이 어째서 함수로 되어 있으며, 객체가 되면 안 되는지에 대한 이야기는 아래를 보시면 있습니다.'
Q1. 위의 문장에서 '객체가 된다'는 것의 의미는 아래와 같이 구현하는 것일까요?
```
class Jan {
 public:
    Jan() { return Month(1); }
    ... 
};
```

그리고 그 다음 페이지 첫 번째 문단에서 객체를 쓰지 않고 함수를 쓴 것에 대한 이유를 설명해주고 있습니다.
Q2. 여기서 '비지역 정적 객체들의 초기화를 믿고 나가는 것은 그 자체로 문제가 있다고요' 라고 하는 것이 이해가 가지 않습니다.

**Comment by shin0343** [comment]
A1. 네 예시로 들어준 코드처럼 객체를 반환하되, 중요한건 싱글턴처럼 static한 Jan 객체가 선언되어있고, 그 객체를 리턴하는 경우를 저자는 말하고 있는걸로 보입니다.
```
class Month
{
  public:
    static Month Jan;
    . . .
};
```

A2. 비지역 정적 객체는 생성되는 시점이 명확하지 않습니다. 그래서 객체 초기화를 믿을 수 없다는 표현으로 설명한걸로 이해했어요.
