### ISSUE TITLE
[항목2-1] p.57 'const의 주소를 잡아내는 것은 합당하지만, enum의 주소를 취하는 일은 불법이며 #define의 주소를 얻는 것 역시 맞지 않습니다. '의 의미

### ISSUE THREAD

**Issue by chae9606** [cppmm-developer/effective_cpp#2]
주소를 취할 일이 없었어서 잘 안 와닿네용.
enum의 주소를 취하려고 하면 어떤 일이 일어나는지 궁금합니다.
간단한 코드로 cosnt, enum, #define 다 실험해보는 예시가 있으면 좋을 것 같아요! :)

**Comment by chae9606** [comment]
해당 문장은 이펙티브 c++ 3판 57pg에 있습니다!

**Comment by hwayoungBaek** [comment]
아래 코드로 const, #define, enum 변수의 주소를 취할 때를 확인해 볼 수 있습니다. 
```
const int const_val = 1;
#define define_val 2
enum { enum_val = 3 };

std::cout << "&const_val: " << const_val << std::endl; 
std::cout << "&define_val: " << &define_val << std::endl; 
std::cout << "&enum_val: " << &enum_val << std::endl;
```


테스트 결과 enum과 #define 선언 변수는 컴파일러에게 상수로 취급되어 &주소 연산자를 사용하지 못한다는 빌드 에러가 나오게 됩니다.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/22655454/215316886-9f3e68ac-06e3-459b-bb2b-e1206ea0ed00.png">
