### ISSUE TITLE
[항목 19-1] 148p. 어떤 종료의 타입 변환을 허용할 것인가?

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#20]
Q1. 140p '어떤 종류의 타입 변환을 허용할 것인가' 문단의 아래서 두 번째 줄에 있는 '비명시호출 생성자'란 무엇을 의미하나요?
explicit 키워드가 앞에 붙지 않는 생성자라고 이해했는데 이게 맞을까요?

Q2. '암시적 변환을 허용하는 클래스'와 '명시적 타입 변환만 허용하는 클래스'에 대한 예시 코드를 작성했습니다. 
혹시 놓치거나 틀린 게 있을까요?
```
// 암시적 타입 변환을 허용하고 싶은 경우
class A {
 public:
    // 1. 생성자에 explicit 키워드를 붙이지 않는다.
    A(int val) : val_{val} {};
    ~A() {};
    
    // 2. 변환함수를 구현한다.
    operator int() const { return val_; };
    
 public:
    int val_;
};

// 명시적 타입 변환만 허용하고 싶은 경우
class B {
 public:
    // 1. 명시호출 생성자만 만든다. (생성자에 explicit 키워드를 붙인다.)
    explicit B(int val) : val_{val} {};
    ~B() {};
    
    // 2. 타입 변환 연산자를 만들지 않는다.
    // operator int() const { return val_; };
    
    // 3. 변환을 맡는 별도 이름의 함수를 만든다.
    const int GetIntB() { return val_; };
    
 public:
    int val_;
};

int main()
{
    // 암시적 형변환 예시 1
    A a1(1);
    std::cout << "a1: " << a1 << std::endl;  // A->int 타입 변환 가능
    
    // 암시적 형변환 예시 2
    double tmp = 2.2;
    A a2 = tmp; // double->A로 변환 가능
    std::cout << "a2: " << a2 << std::endl;


    // 명시적 형변환 예시 1
    B b1(4);
    //std::cout << "b1:" << b1 << std::endl;  // error. B에서 출력이 가능한 다른 타입으로 변환 시도했으나 실패
    
    // 명시적 형변환 예시 2
    double tmp2 = 5.5;
    //B b2 = tmp2;  // error. double에서 B로 타입 변환 실패
    
    // 명시적 형변환 예시 3
    B b3(6);
    std::cout << "b3: " << b3.GetIntB() << std::endl;  // B 클래스에서 제공되는 타입 변환만 가능
    
    return 0;
}
```
실행 결과
```
a1: 1
a2: 2
b3: 6
```

**Comment by shin0343** [comment]
Q1. 140p '어떤 종류의 타입 변환을 허용할 것인가' 문단의 아래서 두 번째 줄에 있는 '비명시호출 생성자'란 무엇을 의미하나요?
explicit 키워드가 앞에 붙지 않는 생성자라고 이해했는데 이게 맞을까요?

-> A1. 네. 저도 expicit 키워드가 붙지 않는 생성자라고 이해했습니다. 문맥상 타입 변환(형변환) 허용을 다루고 있기 때문에 explicit이 없는 생성자를 의미하는 것으로 보여요.

**Comment by shin0343** [comment]
Q2. '암시적 변환을 허용하는 클래스'와 '명시적 타입 변환만 허용하는 클래스'에 대한 예시 코드를 작성했습니다.
혹시 놓치거나 틀린 게 있을까요?

-> A2. 정확한 코드 같습니다! 덕분에 변환 연산자에 대해서 찾아보게 되었네요. 오히려 책에서의 예시는 <암시적 형변환 예시2> 같은 변환 생성자 케이스 만을 보여줘서 제가 놓쳤던 부분 같습니다.
```
// 암시적 형변환 예시 2
    double tmp = 2.2;
    A a2 = tmp; // double->A로 변환 가능
    std::cout << "a2: " << a2 << std::endl;
```

변환 연산자 글을 보다보니 C++ 11부터는 변환 연산자에도 explicit 키워드를 붙일 수 있게 되었다고 하네요! 심지어 의도치 않은 문제 발생 예방을 위해 변환 연산자에 explicit을 붙이는 것이 권장사항처럼 쓰여서, 개인적으로 코딩 습관으로 두면 좋겠다 싶었어요.
(https://psychoria.tistory.com/41)

**Comment by hwayoungBaek** [comment]
저는 이번 항목덕분에 처음으로 타입변환연산자에 대해 알게 됐어요
오 좋은 정보 감사합니다. 의도치않은 형변환을 막기위해 타입변환연산자 앞에 explicit 키워드를 붙이는 코딩 습관👍 저도 기억해놓겠습니다
