### ISSUE TITLE
[항목 23-1] 1654p 예제 clearEventything 함수의 캡슐화?

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#22]
165p 두번째 단락에서 멤버 버전 clearEverything 함수에 대해 캡슐화면에서 형편없다고 설명하고 있습니다.
그러나 저는 clearEverything 함수가 왜 캡슐화면에서 형편없는지 이해가 가지 않습니다.
함수 내부 로직을 보면 WebBrowser의 데이터나 상태 변경이 없고, 여전히 사용자로부터의 접근을 보호해주고 있다고 생각합니다.

**Comment by chae9606** [comment]
저자는 clearEverything 함수의 캡슐화 방해 '가능성' 때문에 캡슐화 면에서 형편없다고 얘기하는 것 같습니다.
clearEverything()과 비멤버, 비프렌드 함수인 clearBrowser()의 차이점은 크게 두 가지 입니다.
1. clearEverything()은 멤버 함수이기 때문에 클래스 내부의 캡슐화된 private 멤버들에 접근할 수 있어 캡슐화 정도가 낮아진다.
2. clearEverything()은 멤버 함수이기 때문에 내부 코드 수정, 삭제 등이 일어나면 많은 사용자에게 영향을 줄 수 있다. clearBrowser()를 수정하면 반면에 제한된 사용자들밖에 영향을 주지 않는다.

예시 코드에서는 clearEverything()이 public으로 선언된 멤버 함수들을 호출하는 함수로 보여 문제가 없어 보이지만, clearEverything()은 위와 같은 가능성을 가지고 있기 때문에 캡슐화 면에서 형편없다고 표현한 것 같습니다!

**Comment by hwayoungBaek** [comment]
이해잘가요! 감사합니당
