### ISSUE TITLE
[항목 27-1] 188p reinterpret_cast는 하부 수준 캐스팅을 위한 용도

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#25]
reinterpret_cast 연산자는 '포인터를 int로 바꾸는 등의 하부 수준 캐스팅을 위해 만들어진 연산자'라고 설명하고 있습니다. 여기서 말하는 '하부 수준 캐스팅'이 잘 와닿지가 않습니다. 설명과 함께 포인터->int 외의 다른 예시도 있을까요?

**Comment by shin0343** [comment]
저도 이 캐스팅 연산자를 써본적이 없어서 사례가 부족하지만..
주로 C기반 코드와 C++기반 코드 간의 저레벨 처리할 때나 패킷통신하여 받은 데이터를 포인터로 변환할 때 reinterpret_cast를 사용한다고 합니다. (void*로의 캐스팅이 가능하므로 그렇다네요)

reinterpret_cast를 사용할 때는
기본 자료형 -> 기본 자료형의 변환은 안되며,
[일반변수 -> 포인터 / 포인터 -> 포인터 / 포인터 -> 일반변수] 꼴의 변환이 가능합니다.

예시1 [int* -> long -> int*]

#include <iostream>

using namespace std;

int main() {
    int* p = new int(100);
    long c = reinterpret_cast<long> (p);
    printf("long c = %ld\n", c);

    int* temp = reinterpret_cast<int *>(c);
    printf("temp = %d\n", *temp);

    return 0;
}

![스크린샷 2023-04-03 오후 11 40 54](https://user-images.githubusercontent.com/25797948/229543530-7fc1f4df-8149-474b-82b5-8bc239cbef25.png)

**Comment by hwayoungBaek** [comment]
코드 예제 너무 좋아요! 이해가 쏙쏙 갑니다! 👍 

위에서 설명한 안된다고 했던 코드(기본연산자->기본연산자)도 추가해놓습니다~
reinterpret_cast를 이용해서 int->long 변환 : ERROR
```
int p = 3;
long c =  reinterpret_cast<long>(p);
printf("long c = %ld\n", c);
```

실행 결과
```
main.cpp: In function ‘int main()’:
main.cpp:21:15: error: invalid cast from type ‘int’ to type ‘long int’
   21 |     long c =  reinterpret_cast<long>(p);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
```

그리고 '하부 수준 캐스팅'에 대한 Chat GPT의 답변 공유합니다.

<em>하부 수준 캐스팅(하위 수준 캐스팅, low-level casting)은 <ins>포인터나 레퍼런스와 같은 메모리 관련 타입들에 대한 캐스팅</ins>을 말합니다. 이런 타입들은 메모리의 특정 위치를 직접 참조하므로, 캐스팅을 잘못 사용하면 프로그램의 메모리 무결성을 해치거나, 예기치 않은 동작을 유발할 수 있습니다.

예를 들어, C 스타일의 캐스팅인 (int)ptr과 같은 코드는 하부 수준 캐스팅에 해당합니다. 이러한 캐스팅은 C++에서는 되도록 사용하지 않는 것이 좋습니다. 대신, C++에서는 static_cast, reinterpret_cast, const_cast와 같은 안전한 스타일의 캐스팅 연산자를 제공합니다.</em>

**Comment by shin0343** [comment]
추가 예시코드 감사합니다!
하부수준이라는게 C스타일 캐스팅과 상통하는 의미였군요.. 모호했던 개념이 잡혔어요!!
