### ISSUE TITLE
[항목 27-2] 191p 캐스팅 클래스 복사

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#27]
캐스팅시에 복사가 일어나나요?

191p에 다음과 같은 코드가 있습니다.
```
static_cast<Window>(*this).onResize();
```
해당 코드를 보며 다음과 같이 설명하고 있습니다. 
"*this를 Window로 캐스팅하는 코드입니다. ... 함수호출이 이루어지는 객체가 글쎄, 현재의 객체가 아니란 말입니다! ... 이 코드에서는 캐스팅이 일어나면서 *this의 기본 클래스 부분에 대한 사본이 임시적으로 만들어지게 되어 있는데, ..."
이 말에 의하면, 캐스팅하면 클래스가 복사 되는건가요??

**Comment by chae9606** [comment]
static_cast를 사용해 파생 클래스의 포인터나 참조자를 기본 클래스로 캐스팅하면 기본 클래스 개체의 임시 복사본이 메모리에 생성될 수 있다고 합니다!

왜냐하면 파생 클래스에는 추가적인 멤버와 함수가 있을 수 있어 객체의 크기가 기본 객체의 크기보다 클 수 있기 때문입니다. 
그래서 컴파일러가 파생 클래스 포인터를 참조를 기본 클래스로 캐스팅 할 때 객체의 기본 클래스 부분을 가리키도록 포인터와 참조를 조정하는데요. 
이때 기본 클래스 객체의 임시 사본이 만들어진다고 합니다!
