### ISSUE TITLE
[항목2-2] p.54 '#define으로 만들어진 상수는 기호 테이블에 이름이 들어가지 않기 때문이다. '의 의미?

### ISSUE THREAD

**Issue by chae9606** [cppmm-developer/effective_cpp#3]
3판 54pg의 중간쯤 있는 문장인데요.
#define으로 만든 ASPECT_RATIO는 기호식 디버거에서 문제가 나타날 소지가 있습니다. 마찬가지로 기호 테이블에 이름이 들어가지 않기 때문입니다.

여기서 왜 기호 테이블에 이름이 들어가지 않는지 궁금해서 생각해봤습니다.
제가 생각한 이유가 맞는지 봐주세요~

#define이 포함된 소스 코드는 전처리기에서 #define된 내용이 컴파일러에 넘어 가기 전에 숫자 상수로 바꾼다.
그 후, 컴파일러가 소스 코드를 컴파일해 오브젝트 파일로 만든다.
오브젝트 파일 안에 기호 테이블 데이터 구조가 존재하고 오브젝트 파일의 여러 항목을 링커가 이해할 수 있는 이름으로 매핑시킨다.
전처리기에서 컴파일 전에 이미 상수로 변경하였기 때문에 오브젝트 파일의 기호 테이블에 들어갈 수 없다.

맞나요~?

**Comment by hwayoungBaek** [comment]
맞는것같습니다👍
