### ISSUE TITLE
[항목2-3] p.57 매크로 함수의 데이터 증가횟수 괴현상 예제

### ISSUE THREAD

**Issue by shin0343** [cppmm-developer/effective_cpp#4]
책에서는 매크로 함수의 인자 증분 값이 달라지는 괴현상을 소개하며 inline함수 사용을 권장하는데요.
왜 Inline함수를 사용해야하는지는 알겠으나, 매크로 함수의 문제 현상을 설명하는 예제가 잘 이해가 안돼요.

CALL_WITH_MAX(++a,b); // a가 두 번 증가합니다.
CALL_WITH_MAX(++a,b+10); // a가 한 번 증가합니다.

위의 두 경우는 왜 증가 횟수가 달라지는 걸까요?

**Comment by chae9606** [comment]
제가 답변드립니당!

int a = 5;
int b = 0;

CALL_WITH_MAX(++a, b);		// 1)
CALL_WITH_MAX(++a, b + 6);	// 2)


1) 함수 호출을 풀어쓰면 f((++a) > (b) ? (++a) : (b)) 와 같아진다. a가 5이고 b가 0이기 때문에 비교하는 시점에 a는 6이고 b는 0이다. a가 더 크기 때문에 ++a를 또 실행한다. 함수가 끝날 때 a는 7이 되고 b는 0이 된다.

2) 함수 호출을 풀어쓰면  f((++a) > (b + 10) ? (++a) : (b + 10))이다. a가 5이고 b는 0이기 때문에 크고 작음을 비교하는 시점에 a는 6으로 증가하고 b는 0이다. b + 10이 a보다 크기 때문에 ++a는 실행되지 않는다. 즉 함수가 끝날 때 a는 6이고 b는 0이다.

**Comment by hwayoungBaek** [comment]
너무 재미있는 실험이에요!

테스트 코드 추가합니다.
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/22655454/215316694-ea8f6232-b610-471a-b4c4-174b302c15f6.png">

추가로 a++가 아닌 ++a 를 테스트 해보았는데 결과가 또 다르네요.
이렇게 줄 경우 a, b 비교를 완료하고 나서야  a증가(a++)를 수행합니다. 따라서 더 큰 값은 b 5가 되고, a는 한 번만 증가된 상태 6으로 리턴됩니다.

**Comment by shin0343** [comment]
깔끔하게 이해됐어요! 감사합니다!!
