### ISSUE TITLE
[항목3-1] p.68-70 상수 함수 안에서 비상수 함수를 호출하는 경우 발생하는 문제에 대하여

### ISSUE THREAD

**Issue by shin0343** [cppmm-developer/effective_cpp#5]
책에서는 비상수 함수 안에서 상수 함수를 호출하는 예시를 들며, 코드 중복을 제거하는 사례를 소개합니다.
p.69후반~p.70초반 내용을 보면 역의 경우, 즉 상수 함수 안에서 비상수 함수를 호출하는 것은 컴파일러와의 약속(논리적 상태를 바꾸지 않겠다고 했던..)을 어기는 것이라고 설명합니다. 이 경우를 실제 코드로 작성하면 컴파일 에러가 발생할까요?

추가 질문) 코드로 작성한다면 아래처럼 작성하는게 맞을까요?

```
const char& operator[] (std::size_t position) const
{
 return static_cast<const TextBlock&> (
  const_cast<char&> (*this)[position]
);
}
```

**Comment by hwayoungBaek** [comment]
상수 함수안에서 비상수 함수를 호출하는 논리상의 코드는 아래와 같습니다.
```
const char& operator[] (std::size_t position) const
  {
      return const_cast<const char&> (
          static_cast<TextBlock&>
           (*this)[position]
          );
  }
```

1) 비상수 객체 TextBlock&로 변환하여
2) 비상수 객체에 대한 operator[] 연산을 수행하고
2) 그것에 대한 리턴값을 const char&로 다시 캐스팅합니다.

그러나 위와 같이 실행할 경우, 상수 객체를 비상수 객체로 변환할 수 없다는 컴파일 에러가 발생하게 됩니다.
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/22655454/215329821-edcee06c-c371-4fe1-af21-9b74c414f50a.png">


P.S. 근데 사실 안좋은 방법이지만 C스타일의 캐스팅을 하면 상수->비상수 변환이 가능합니다.
```
const char& operator[] (std::size_t position) const  // 상수 함수안에서 비상수 함수를 호출함
{
    return const_cast<const char&> (
            ((TextBlock&)(*this))[position]
        );
}
```
