### ISSUE TITLE
[항목 3-2] p.62-63 비상수 멤버와 상수 멤버 호출

### ISSUE THREAD

**Issue by chae9606** [cppmm-developer/effective_cpp#6]
예시)
class Test {
public:
...

public:
    const char& operator[](std::size_t position) const	//상수 객체에 대한 operator[] 1!
    { return text[position]; }
    
    char& operator[](std::size_t position)	//비상수 객체에 대한 operator[] 2!
    { return text[position]; }

private:
    std::string text;
};

int main()
{
    Test t("Hello");
    std::cout << t[0];	//operator[] 비상수 멤버 호출 2!
    
    const Test w("World");
    std::cout << w[0];	//operator[] 상수 멤버 호출 1!
}

여기서 질문이 있습니다.
1. 만약 상수 객체를 생성했는데 비상수 객체에 대한 operator[]만 있고 상수 객체에 대한 operator[]가 없다면 어떻게 되나요?
2. 만약 비상수 객체를 생성했는데 상수 객체에 대한 operator[]만 있고 비상수 객체에 대한 operator[]가 없다면 어떻게 되나요?

궁금합니다~!

**Comment by chae9606** [comment]
공부하는 김에 한번 해봤습니다~!!
* 1번 케이스는 컴파일 오류가 발생합니다.
-> E0349 이러한 피연산자와 일치하는 "[] 연산자가 없습니다.
만약 상수 객체를 생성해놓고 비상수 함수를 호출하려고 하면 아래와 같은 오류가 발생합니다.
-> E1086 개체에 멤버 함수 "~"와 호환되지 않는 형식 한정자가 있습니다.

* 2번 케이스는 컴파일도 되고 실행도 잘 됩니다. 왜그럴까요?!?!

[Sample Code]
#include <iostream>
class TestBlock {
public:
    TestBlock(std::string temp)
    {
        this->pText = (char *)temp.c_str();
    }
    char* getText(void)
    {
        return this->pText;
    }
    char& operator[](std::size_t position)
    {
        return pText[position];
    }
    
private:
    char* pText;
};

int main()
{
    const TestBlock tb("Hello");
    char* pc = &tb[0];
    *pc = 'J';
    std::cout << tb.getText() << std::endl;
}

**Comment by hwayoungBaek** [comment]
Q. 2. 만약 비상수 객체를 생성했는데 상수 객체에 대한 operator[]만 있고 비상수 객체에 대한 operator[]가 없다면 어떻게 되나요?
     2번 케이스는 컴파일도 되고 실행도 잘 됩니다. 왜그럴까요?!?!

A. 2번 케이스의 경우, 비상수 객체에 대한 [] 요청을 하였으나, 상수 객체에 대한 []가 동작을 합니다.
따라서 상수 값 출력까지는 동작하지만, 해당 주소에 다른 값 대입은 에러가 발생하게 됩니다.
<img width="946" alt="image" src="https://user-images.githubusercontent.com/22655454/215328994-e1ebb484-5b91-426a-bdf7-35a17bd120a9.png">
