### ISSUE TITLE
[항목 4-1] 73p. 기본 제공 타입 객체의 초기화와 대입

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#7]
책에서 ‘기본제공 타입의 객체는 초기화와 대입에 걸리는 비용의 차이가 없지만’ 이라고 나와있는데, 그 이유가 궁금합니다.

**Comment by shin0343** [comment]
사용자가 정의한 타입의 객체는 별도의 생성자가 호출되어 임시 객체가 만들어지고, 그 임시 객체를 대입연산자를 통해서 대입하는 형태가 되어 비용이 커집니다. 생성자 내용이 복잡할수록 그 비용이 더욱 커질수도 있겠지요.

반면, 기본제공 타입의 객체(정수형, 부동 소수점형, void형)은 primitive하여 대입할 때에 임시 객체를 만들어서 복사하는 과정을 거치지 않습니다. 즉, 복사 비용이 고정되어 있고 그 마저도 적은 비용을 가집니다.

이러한 차이로 인해서 저자가 ‘기본제공 타입의 객체는 초기화와 대입에 걸리는 비용의 차이가 없지만’ 이라는 표현을 사용한 것으로 보입니다.
