### ISSUE TITLE
[항목 4-2] 78p. 참조자 반환 함수 인라인화

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#8]
책에서 참조자 반환 함수를 인라인화하면 (내부적으로 정적 객체를 쓰기 때문에) 다중스레드 시스템에서는 동작에 장애가 생길 수 있다고 하는데, 인라인함수를 쓸 때와 일반 함수를 쓸 때의 차이점에 따른 다중 스레드 시스템 동작 설명 부탁드립니다.

**Comment by shin0343** [comment]
우선, 일반함수와 인라인함수 모두 A스레드가 호출하여 사용하고 있는 참조자의 원본 객체를 B스레드가 메모리 해제하는 경우, 동작 안정성에 문제가 발생합니다. 그래서 참조자 반환 함수 대신 함수 내에서 새 객체를 생성하여 그 객체를 반환하는 것이 권장됩니다. (아래코드 참고)

`inline const Rational operator*(const Rational& lhs, const Rational& rhs) {
    return Rational(lhs,rhs);
}`

인라인함수에서만 발생할 수 있는 문제 상황 아직 발견하지 못했네요😂 추후 업데이트하겠습니다!

**Comment by hwayoungBaek** [comment]
제 질문 자체가 잘못됐던 것 같습니다ㅜㅜ

"참조자 반환 함수를 인라인화하면 (내부적으로 정적 객체를 쓰기 때문에) 다중 스레드 시스템에서는 동작에 장애가 생길 수 있다" 의 의미를 참조자 반환함수는 항상 내부적으로 정적 객체를 쓴다는줄 알고 이해가 안갔는데
책의 해당 문구 위에 예시 코드에서 내부적으로 정적 객체를 사용하고 있는 것이었습니다.

```
Directory& tempDir() {
    static Directory td;
    return td;
}
```
